[package]
name = "rsynapse-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["full"]}
zbus = "4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
