[package]
name = "rsynapse-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
zbus = "4"
anyhow = "1"
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
rsynapse-plugin = { path = "../rsynapse-plugin" }
